# Generated by Django 4.0.1 on 2022-01-10 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articul', models.PositiveIntegerField(unique=True)),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
            ],
        ),
    ]
